name: Deploy

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: liberica
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.6
          cache-disabled: true
      - run: gradle build
      - run: java -jar build/libs/demo-0.0.1-SNAPSHOT.jar
      
